name: my first pipeline

on: workflow_dispatch

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"
        
      - name: install java
        uses: actions/setup-java@v5
        with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '17'

      
